branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: impedance-analyzer-env
global:
  application_name: impedance-analyzer
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
